# Generated by Django 4.2.4 on 2023-08-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('races', models.IntegerField(default=0)),
                ('favCharacter', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Time won')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioTracker.players')),
            ],
        ),
    ]
