# Generated by Django 4.2.5 on 2023-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.CharField(max_length=50)),
                ('mapName', models.CharField(max_length=50)),
            ],
        ),
    ]
