# Generated by Django 4.2.4 on 2023-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioTracker', '0003_alter_players_favcharacter_alter_wins_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
