# Generated by Django 4.2.4 on 2023-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioTracker', '0004_alter_players_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
